### ISSUE TITLE
Make sample-docker-app working for arm64 architecture

### ISSUE THREAD

**Issue by getlarge** [Actyx/quickstart#13]
Hey, first of all, thanks for the quickstart that works great to demonstrate your tools.

I wished to know if you intend to make your quickstart docker-app works for raspberry pi, while building from a local machine which is NOT a raspberry pi ?

It is one of my requirement and maybe other people could be interested to work with the same setup.

It would be an occasion to demonstrate how to build on multiple architectures in the app manifest and in your tutorial there could be a step to use a RPi as second device.

If you're interested i can create a PR.

**Comment by rkuhn** [comment]
Thanks for the kind words @getlarge and sorry for the late reply! Yes, building on a “real” machine for a pi makes perfect sense, it would be great to document that. As far as we test things, it currently requires at least a pi3, which one have you tried? A PR would be awesome in any case!

**Comment by getlarge** [comment]
I started to play with ActyxOS on RPi3 (which worked well), but in the meantime a RPi4 arrived so i only made the build/deployment on that RPi4. 
I can try the deployment on the RPi3 if you need confirmation that it works.
